# 02 · 赛程爬虫 + 批量入库

## 这个 notebook 在做什么？

01 解决了「**单场**怎么爬」，02 解决「**全季**怎么爬」。

中间需要一个桥梁——**赛程接口**：从 `league_id`（赛事 ID）出发，拉到这个赛季的**所有 battle_id**，然后调 01 写好的 `fetch_battle()` 批量爬。

## 为什么要分成两个 notebook？

你之前 D 盘的项目，单场逻辑和批量逻辑混在一个文件里，结果：
- 改单场逻辑要改批量代码
- 改批量逻辑要担心影响单场
- 调试时要么全跑要么全不跑，没法局部验证

**关注点分离**——单场归单场（已沉淀到 `api_client.py`），赛程归赛程（这个 notebook 处理）。

## 跑完 notebook，你应该收获什么？

1. ✅ `fetch_schedule(league_id)` 函数：拉某赛季所有 battle_id
2. ✅ `data/processed/schedule.csv`：赛程总表（一行 = 一场比赛）
3. ✅ `data/raw/` 下囤了几十到上百个原始 JSON
4. ✅ 失败列表（哪些场没爬下来，为什么）

## 工作前提

> notebook 00 步骤 8 必须已经完成——**你已经知道赛程接口长什么样**（SSR 还是异步？URL 是什么？）。
> 如果还没，回去补这一步。

---
## 步骤 1 · 准备工作

### 思路

这次要跨文件夹 import `src` 下的模块。Python 的 import 机制有个坑：notebook 默认只能 import **同目录或 site-packages 里**的东西。

要想 import `src.crawler.api_client`，就得告诉 Python：「项目根目录也是个搜索路径」。

```python
import sys
from pathlib import Path
sys.path.insert(0, str(Path('..').resolve()))
```

`Path('..')` = 上一级（项目根目录），`.resolve()` = 转成绝对路径。这样 `from src.xxx import yyy` 就能用了。

In [28]:
# TODO 1.1：导包 + 加 sys.path

import sys
from pathlib import Path
sys.path.insert(0, str(Path('..').resolve()))#sys.path是列表，0就是插在最前面。

# 然后导入：requests, json, pandas, tqdm.auto.tqdm
import requests
import json
import pandas as pd
from tqdm import tqdm

In [29]:
# TODO 1.2：从 src 导入 fetch_battle 并验证
# 调一次确保还能跑（顺便看缓存命中是否生效——不应该再走网络）

# from src.crawler.api_client import fetch_battle
# data = fetch_battle('1038107152_18_1742644777')
# print(data['code'])

from src.crawler.api_client import fetch_battle
data = fetch_battle('736117264_10_1777089898')

2026-05-09 23:26:55 | src.crawler.api_client | INFO | [命中缓存，736117264_10_1777089898]

---
## 步骤 2 · 写赛程爬虫

### 思路

根据你 notebook 00 步骤 8 的结论，分两条路：

**情况 A：赛程页是 SSR（HTML 里直接有数据）**

```python
import re
html = requests.get(schedule_url).text
# 用正则或 BeautifulSoup 抠出比赛信息
```

**情况 B：赛程是异步 JSON 接口**

```python
resp = requests.get(api_url, headers=headers)
data = resp.json()
# 一般 data['data']['list'] 之类的路径里能找到比赛列表
```

### 目标产出

不管哪种来源，最终都要产出**统一格式**的 list：

```python
[
    {
        'battle_id': '1038107152_18_1742644777',
        'match_id': '2026042501',          # 一场比赛的 ID（包含多局）
        'team_a_name': 'AG超玩会',
        'team_b_name': 'eStar',
        'start_time': '2026-04-25 18:00',
        'game_seq': 1,                      # 这是 BO 系列的第几局
        ...
    },
    ...
]
```

### 关键点

> **一场比赛 = 多局 = 多个 battle_id**。BO5 一场最多 5 个 battle_id，BO7 最多 7 个。要把每局都展开成一行，因为 `fetch_battle` 是按 battle_id 拉数据的。

In [30]:
# TODO 2.1：写 fetch_schedule(league_id) 函数
# 输入：赛事 ID（int），如 20260002
# 输出：list of dict，每个 dict 至少含 battle_id / match_id / 两支队 / 时间
#
# 实现思路（根据你 00 步骤 8 的结论选一种）：
#   - 路径 A（SSR）：抠 HTML
#   - 路径 B（异步）：直接调那个 JSON 接口
#
# 提示：
#   - 异步接口的 Headers 通常和单场接口不一样，要 F12 重新看
#   - 返回的 JSON 嵌套很深，多用 print 探索结构
#   - 用 pd.json_normalize 一行展平，比手动 dict 推导快
HEADERS = {
        "User-Agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/128.0.0.0 Mobile Safari/537.36 Edg/128.0.0.0",
        "Accept": "application/json, text/plain, */*",
        "Referer": "https://pvp.qq.com/",
        "Origin": "https://pvp.qq.com",
    }
def fetch_league(league_id):
	#赛程url
    league_url = f"https://prod.comp.smoba.qq.com/leaguesite/matches/open?league_id={league_id}"

    league_list = []

    response = requests.get(url=league_url, headers=HEADERS,timeout=15)
    data_league = response.json()

    for i in range(len(data_league['results'])):
        league_list.append(data_league['results'][i])

    return league_list

In [31]:
fetch_league(20260002)

[{'match_id': '2026042501',
  'league_id': '20260002',
  'camp1': {'team_id': '10005',
   'team_name': 'KSG',
   'team_icon': 'https://smobatv-pic.tga.qq.com/e7f3ca48aa29a89c5cf7e04d7f83534f.png',
   'is_win': False,
   'score': 1,
   'rank': 0,
   'team_abbreviation': 'KSG'},
  'camp2': {'team_id': '10017',
   'team_name': '广州TTG',
   'team_icon': 'https://smhtv-pic.tga.qq.com/0a05fdfba20fa3823db5c8c44fae6abe.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'TTG'},
  'bo': 5,
  'win_camp': 2,
  'status': 2,
  'start_time': '2026-04-25 12:00:00',
  'end_time': '2026-04-25 14:12:39',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W1D1',
  'match_battle_video_list': [{'battle_id': '736117264_10_1777089898',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'e3237udgb2z',
      'video_url': 'https://v.qq.com/x/page/e3237udgb2z.html'}]},
   {'battle_id': '736117264_11_1777091838',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'o32374fegf5',
      'video_url': 'https://v.qq.com/x/page/o32374fegf5.html'}]},
   {'battle_id': '736117264_12_1777093747',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'p3237qnfzpk',
      'video_url': 'https://v.qq.com/x/page/p3237qnfzpk.html'}]},
   {'battle_id': '736117264_13_1777095778',
    'battle_seq': 4,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'l3238j2y8jt',
      'video_url': 'https://v.qq.com/x/page/l3238j2y8jt.html'}]}]},
 {'match_id': '2026042502',
  'league_id': '20260002',
  'camp1': {'team_id': '10002',
   'team_name': '上海EDG.M',
   'team_icon': 'https://smhtv-pic.tga.qq.com/7209fb2509e991052852dd872981c8f3.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'EDG.M'},
  'camp2': {'team_id': '12401',
   'team_name': '青训潜渊',
   'team_icon': 'https://smobatv-pic.tga.qq.com/ec90dbb1920060e848bbc745a39e8647.png',
   'is_win': False,
   'score': 1,
   'rank': 0,
   'team_abbreviation': '青训潜渊'},
  'bo': 5,
  'win_camp': 1,
  'status': 2,
  'start_time': '2026-04-25 14:30:00',
  'end_time': '2026-04-25 16:51:32',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W1D2',
  'match_battle_video_list': [{'battle_id': '736117264_14_1777099889',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'd32382qxtsq',
      'video_url': 'https://v.qq.com/x/page/d32382qxtsq.html'}]},
   {'battle_id': '736117264_15_1777101864',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'a3238tm2fis',
      'video_url': 'https://v.qq.com/x/page/a3238tm2fis.html'}]},
   {'battle_id': '736117264_16_1777103765',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'z32384qtwu2',
      'video_url': 'https://v.qq.com/x/page/z32384qtwu2.html'}]},
   {'battle_id': '736117264_17_1777105595',
    'battle_seq': 4,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'y3238bb6x0r',
      'video_url': 'https://v.qq.com/x/page/y3238bb6x0r.html'}]}]},
 {'match_id': '2026042503',
  'league_id': '20260002',
  'camp1': {'team_id': '12402',
   'team_name': '重庆科技大学',
   'team_icon': 'https://smobatv-pic.tga.qq.com/bc8e1e29f9fdf24468d9f8a87fd7047f.png',
   'is_win': False,
   'score': 0,
   'rank': 0,
   'team_abbreviation': '重庆科技大学'},
  'camp2': {'team_id': '10910',
   'team_name': 'WST',
   'team_icon': 'https://smobatv-pic.tga.qq.com/819cba4c185dbb7dd75a1827058043bb.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'WST'},
  'bo': 5,
  'win_camp': 2,
  'status': 2,
  'start_time': '2026-04-25 18:30:00',
  'end_time': '2026-04-25 19:51:38',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W1D3',
  'match_battle_video_list': [{'battle_id': '736117264_18_1777113272',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'q3238igrb65',
      'video_url': 'https://v.qq.com/x/page/q3238igrb65.html'}]},
   {'battle_id': '736117264_19_1777114949',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'w32382ewna7',
      'video_url': 'https://v.qq.com/x/page/w32382ewna7.html'}]},
   {'battle_id': '736117264_21_1777117059',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'z3238tkou08',
      'video_url': 'https://v.qq.com/x/page/z3238tkou08.html'}]}]},
 {'match_id': '2026042504',
  'league_id': '20260002',
  'camp1': {'team_id': '12403',
   'team_name': '阿里巴巴PKQ',
   'team_icon': 'https://smobatv-pic.tga.qq.com/bae16422b3e9148dc176bb857cf7de03.png',
   'is_win': False,
   'score': 0,
   'rank': 0,
   'team_abbreviation': '阿里巴巴PKQ'},
  'camp2': {'team_id': '10031',
   'team_name': '杭州LGD.NBW',
   'team_icon': 'https://smhtv-pic.tga.qq.com/a29bcb1a579369888cc9a87637274822.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'LGD'},
  'bo': 5,
  'win_camp': 2,
  'status': 2,
  'start_time': '2026-04-25 21:00:00',
  'end_time': '2026-04-25 21:38:21',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W1D4',
  'match_battle_video_list': [{'battle_id': '736117264_22_1777120389',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'y32386sf29p',
      'video_url': 'https://v.qq.com/x/page/y32386sf29p.html'}]},
   {'battle_id': '736117264_23_1777122032',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'l3238usrems',
      'video_url': 'https://v.qq.com/x/page/l3238usrems.html'}]},
   {'battle_id': '736117264_24_1777123595',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'l32387uafuw',
      'video_url': 'https://v.qq.com/x/page/l32387uafuw.html'}]}]},
 {'match_id': '2026042601',
  'league_id': '20260002',
  'camp1': {'team_id': '10903',
   'team_name': '桐乡情久',
   'team_icon': 'https://smhtv-pic.tga.qq.com/f4fc888e840157eaa4bc7b261f71e835.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': '情久'},
  'camp2': {'team_id': '10028',
   'team_name': '长沙TES.A',
   'team_icon': 'https://smhtv-pic.tga.qq.com/48f18204fa257197ec49bb6345d14a33.png',
   'is_win': False,
   'score': 2,
   'rank': 0,
   'team_abbreviation': 'TES.A'},
  'bo': 5,
  'win_camp': 1,
  'status': 2,
  'start_time': '2026-04-26 12:00:00',
  'end_time': '2026-04-26 14:28:56',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W2D1',
  'match_battle_video_list': [{'battle_id': '736117264_26_1777176389',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'v3238h5o4pn',
      'video_url': 'https://v.qq.com/x/page/v3238h5o4pn.html'}]},
   {'battle_id': '736117264_27_1777178528',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'y3238lma5pe',
      'video_url': 'https://v.qq.com/x/page/y3238lma5pe.html'}]},
   {'battle_id': '736117264_28_1777180478',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'v32383vw972',
      'video_url': 'https://v.qq.com/x/page/v32383vw972.html'}]},
   {'battle_id': '736117264_29_1777182144',
    'battle_seq': 4,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'a3238j9d9nt',
      'video_url': 'https://v.qq.com/x/page/a3238j9d9nt.html'}]},
   {'battle_id': '736117264_30_1777183470',
    'battle_seq': 5,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'f3238c34o5l',
      'video_url': 'https://v.qq.com/x/page/f3238c34o5l.html'}]}]},
 {'match_id': '2026042602',
  'league_id': '20260002',
  'camp1': {'team_id': '10003',
   'team_name': '北京WB',
   'team_icon': 'https://smhtv-pic.tga.qq.com/75b41b2357febfa17764f8bc1f423d2c.png',
   'is_win': False,
   'score': 2,
   'rank': 0,
   'team_abbreviation': 'WB'},
  'camp2': {'team_id': '10601',
   'team_name': '无锡TCG',
   'team_icon': 'https://smhtv-pic.tga.qq.com/b271c7d4e606561873604b2f58bcac7d.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'TCG'},
  'bo': 5,
  'win_camp': 2,
  'status': 2,
  'start_time': '2026-04-26 14:30:00',
  'end_time': '2026-04-26 17:27:30',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W2D2',
  'match_battle_video_list': [{'battle_id': '736117264_31_1777187214',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'h3239hasbxk',
      'video_url': 'https://v.qq.com/x/page/h3239hasbxk.html'}]},
   {'battle_id': '736117264_32_1777188987',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'o3239bhdz26',
      'video_url': 'https://v.qq.com/x/page/o3239bhdz26.html'}]},
   {'battle_id': '736117264_33_1777190822',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'r3239qthfo9',
      'video_url': 'https://v.qq.com/x/page/r3239qthfo9.html'}]},
   {'battle_id': '736117264_34_1777192390',
    'battle_seq': 4,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'w32397857o2',
      'video_url': 'https://v.qq.com/x/page/w32397857o2.html'}]},
   {'battle_id': '736117264_35_1777194471',
    'battle_seq': 5,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'd3239lgqvj1',
      'video_url': 'https://v.qq.com/x/page/d3239lgqvj1.html'}]}]},
 {'match_id': '2026042603',
  'league_id': '20260002',
  'camp1': {'team_id': '12202',
   'team_name': 'SYG',
   'team_icon': 'https://smobatv-pic.tga.qq.com/3eaef9a24b7181b25951d54a1a13bfe0.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'SYG'},
  'camp2': {'team_id': '12404',
   'team_name': 'ZDC',
   'team_icon': 'https://smobatv-pic.tga.qq.com/9ae79e891ce036c058a746e6b1067619.png',
   'is_win': False,
   'score': 2,
   'rank': 0,
   'team_abbreviation': 'ZDC'},
  'bo': 5,
  'win_camp': 1,
  'status': 2,
  'start_time': '2026-04-26 18:30:00',
  'end_time': '2026-04-26 22:00:59',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W2D3',
  'match_battle_video_list': [{'battle_id': '736117264_36_1777201256',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'm3239s73i93',
      'video_url': 'https://v.qq.com/x/page/m3239s73i93.html'}]},
   {'battle_id': '736117264_37_1777203203',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'y3239c6xp3w',
      'video_url': 'https://v.qq.com/x/page/y3239c6xp3w.html'}]},
   {'battle_id': '736117264_38_1777205445',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'q3239ha24ny',
      'video_url': 'https://v.qq.com/x/page/q3239ha24ny.html'}]},
   {'battle_id': '736117264_39_1777207738',
    'battle_seq': 4,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'd32392szavx',
      'video_url': 'https://v.qq.com/x/page/d32392szavx.html'}]},
   {'battle_id': '736117264_40_1777209524',
    'battle_seq': 5,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'y3239x4jmvb',
      'video_url': 'https://v.qq.com/x/page/y3239x4jmvb.html'}]}]},
 {'match_id': '2026042604',
  'league_id': '20260002',
  'camp1': {'team_id': '10018',
   'team_name': '济南RW侠',
   'team_icon': 'https://smobatv-pic.tga.qq.com/11ba263f0d5d6fd422c4efb14df3ad62.png',
   'is_win': False,
   'score': 2,
   'rank': 0,
   'team_abbreviation': 'RW侠'},
  'camp2': {'team_id': '10027',
   'team_name': '成都AG超玩会',
   'team_icon': 'https://smhtv-pic.tga.qq.com/02e0582db3b0766ad6fab97e95743e6c.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'AG'},
  'bo': 5,
  'win_camp': 2,
  'status': 2,
  'start_time': '2026-04-26 21:00:00',
  'end_time': '2026-04-27 01:12:47',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W2D4',
  'match_battle_video_list': [{'battle_id': '736117264_41_1777214738',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'n3239c6n816',
      'video_url': 'https://v.qq.com/x/page/n3239c6n816.html'}]},
   {'battle_id': '736117264_42_1777216972',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'b3239p5xvz4',
      'video_url': 'https://v.qq.com/x/page/b3239p5xvz4.html'}]},
   {'battle_id': '736117264_43_1777218912',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'j3239cioxhk',
      'video_url': 'https://v.qq.com/x/page/j3239cioxhk.html'}]},
   {'battle_id': '736117264_44_1777220644',
    'battle_seq': 4,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'a323908j0mj',
      'video_url': 'https://v.qq.com/x/page/a323908j0mj.html'}]},
   {'battle_id': '736117264_45_1777222317',
    'battle_seq': 5,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 't3239ovca3u',
      'video_url': 'https://v.qq.com/x/page/t3239ovca3u.html'}]}]},
 {'match_id': '2026042701',
  'league_id': '20260002',
  'camp1': {'team_id': '10006',
   'team_name': '武汉eStarPro',
   'team_icon': 'https://smobatv-pic.tga.qq.com/ad7441d6a83f41e0efe1dbd23d9bacad.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'ES'},
  'camp2': {'team_id': '12405',
   'team_name': 'GKE',
   'team_icon': 'https://smobatv-pic.tga.qq.com/ead9f779314e86fd655016e26745085a.png',
   'is_win': False,
   'score': 0,
   'rank': 0,
   'team_abbreviation': 'GKE'},
  'bo': 5,
  'win_camp': 1,
  'status': 2,
  'start_time': '2026-04-27 12:00:00',
  'end_time': '2026-04-27 13:31:00',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W3D1',
  'match_battle_video_list': [{'battle_id': '736117264_48_1777262688',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'c3239p2lcdy',
      'video_url': 'https://v.qq.com/x/page/c3239p2lcdy.html'}]},
   {'battle_id': '736117264_49_1777264603',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'w3239lu2i9t',
      'video_url': 'https://v.qq.com/x/page/w3239lu2i9t.html'}]},
   {'battle_id': '736117264_50_1777266554',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'z3239ydqs2d',
      'video_url': 'https://v.qq.com/x/page/z3239ydqs2d.html'}]}]},
 {'match_id': '2026042702',
  'league_id': '20260002',
  'camp1': {'team_id': '10905',
   'team_name': 'LTG',
   'team_icon': 'https://smobatv-pic.tga.qq.com/9382249350922f6c8424079d4bf46071.png',
   'is_win': False,
   'score': 1,
   'rank': 0,
   'team_abbreviation': 'LTG'},
  'camp2': {'team_id': '10008',
   'team_name': '深圳DYG',
   'team_icon': 'https://smhtv-pic.tga.qq.com/221a9ffe2de016e02e146465ed57ce73.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'DYG'},
  'bo': 5,
  'win_camp': 2,
  'status': 2,
  'start_time': '2026-04-27 14:30:00',
  'end_time': '2026-04-27 16:25:26',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W3D2',
  'match_battle_video_list': [{'battle_id': '736117264_51_1777270365',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'i3239aauwoq',
      'video_url': 'https://v.qq.com/x/page/i3239aauwoq.html'}]},
   {'battle_id': '736117264_52_1777272165',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'f3240dbynbm',
      'video_url': 'https://v.qq.com/x/page/f3240dbynbm.html'}]},
   {'battle_id': '736117264_53_1777274294',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'p3240yskb81',
      'video_url': 'https://v.qq.com/x/page/p3240yskb81.html'}]},
   {'battle_id': '736117264_54_1777277113',
    'battle_seq': 4,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'i3240odg3j1',
      'video_url': 'https://v.qq.com/x/page/i3240odg3j1.html'}]}]},
 {'match_id': '2026042703',
  'league_id': '20260002',
  'camp1': {'team_id': '10009',
   'team_name': '上海RNG.M',
   'team_icon': 'https://smhtv-pic.tga.qq.com/c2dfe93f6e1cabb13512d3fb42d94051.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': 'RNG.M'},
  'camp2': {'team_id': '12408',
   'team_name': 'BTR',
   'team_icon': 'https://smobatv-pic.tga.qq.com/8b1986ae9789a75bb1fec25b23f807ff.png',
   'is_win': False,
   'score': 0,
   'rank': 0,
   'team_abbreviation': 'BTR'},
  'bo': 5,
  'win_camp': 1,
  'status': 2,
  'start_time': '2026-04-27 18:30:00',
  'end_time': '2026-04-27 19:48:07',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W3D3',
  'match_battle_video_list': [{'battle_id': '736117264_55_1777286089',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'q3240kv2gt7',
      'video_url': 'https://v.qq.com/x/page/q3240kv2gt7.html'}]},
   {'battle_id': '736117264_56_1777287965',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'f32407lewnl',
      'video_url': 'https://v.qq.com/x/page/f32407lewnl.html'}]},
   {'battle_id': '736117264_57_1777289572',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'm3240f4ij7v',
      'video_url': 'https://v.qq.com/x/page/m3240f4ij7v.html'}]}]},
 {'match_id': '2026042704',
  'league_id': '20260002',
  'camp1': {'team_id': '10001',
   'team_name': '重庆狼队',
   'team_icon': 'https://smhtv-pic.tga.qq.com/a85f1428dd1ef3eaeeb5e203f17b9b25.png',
   'is_win': True,
   'score': 3,
   'rank': 0,
   'team_abbreviation': '狼队'},
  'camp2': {'team_id': '12410',
   'team_name': '好厚米',
   'team_icon': 'https://smobatv-pic.tga.qq.com/514be0f3714547d1ab67b341bc259fda.png',
   'is_win': False,
   'score': 0,
   'rank': 0,
   'team_abbreviation': '好厚米'},
  'bo': 5,
  'win_camp': 1,
  'status': 2,
  'start_time': '2026-04-27 21:00:00',
  'end_time': '2026-04-27 22:05:25',
  'match_address': '北京',
  'match_desc': '',
  'match_stage_seq': 0,
  'match_stage_name': 'dbtts',
  'match_stage_desc': '单败淘汰赛',
  'cc_match_id': 'KCC2026M1W3D4',
  'match_battle_video_list': [{'battle_id': '736117264_58_1777293318',
    'battle_seq': 1,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 's3240bwyso8',
      'video_url': 'https://v.qq.com/x/page/s3240bwyso8.html'}]},
   {'battle_id': '736117264_59_1777295254',
    'battle_seq': 2,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'k324053jjad',
      'video_url': 'https://v.qq.com/x/page/k324053jjad.html'}]},
   {'battle_id': '736117264_60_1777297594',
    'battle_seq': 3,
    'video_list': [{'video_channel': 'tencent_video',
      'video_id': 'z3240sjfh17',

In [32]:
# TODO 2.2：测试 + 转 DataFrame
# schedule_list = fetch_schedule(20260002)
# schedule_df = pd.DataFrame(schedule_list)
# print(schedule_df.shape)
# schedule_df.head()
#
# 自检：
#   - 行数对不对？挑战者杯 2026 大概 16 队 × 单循环 ≈ 几十场
#   - battle_id 是不是唯一？（df['battle_id'].duplicated().sum() 应该是 0）
#   - 时间字段是字符串还是时间戳？


schedule_list = fetch_league(20260002)
schedule_df = pd.DataFrame(schedule_list)

In [33]:
schedule_df.shape

(38, 16)

In [34]:
schedule_df.head()

,match_id,league_id,camp1,camp2,bo,win_camp,status,start_time,end_time,match_address,match_desc,match_stage_seq,match_stage_name,match_stage_desc,cc_match_id,match_battle_video_list
0,2026042501,20260002,"{'team_id': '10005', 'team_name': 'KSG', 'team...","{'team_id': '10017', 'team_name': '广州TTG', 'te...",5,2,2,2026-04-25 12:00:00,2026-04-25 14:12:39,北京,,0,dbtts,单败淘汰赛,KCC2026M1W1D1,"[{'battle_id': '736117264_10_1777089898', 'bat..."
1,2026042502,20260002,"{'team_id': '10002', 'team_name': '上海EDG.M', '...","{'team_id': '12401', 'team_name': '青训潜渊', 'tea...",5,1,2,2026-04-25 14:30:00,2026-04-25 16:51:32,北京,,0,dbtts,单败淘汰赛,KCC2026M1W1D2,"[{'battle_id': '736117264_14_1777099889', 'bat..."
2,2026042503,20260002,"{'team_id': '12402', 'team_name': '重庆科技大学', 't...","{'team_id': '10910', 'team_name': 'WST', 'team...",5,2,2,2026-04-25 18:30:00,2026-04-25 19:51:38,北京,,0,dbtts,单败淘汰赛,KCC2026M1W1D3,"[{'battle_id': '736117264_18_1777113272', 'bat..."
3,2026042504,20260002,"{'team_id': '12403', 'team_name': '阿里巴巴PKQ', '...","{'team_id': '10031', 'team_name': '杭州LGD.NBW',...",5,2,2,2026-04-25 21:00:00,2026-04-25 21:38:21,北京,,0,dbtts,单败淘汰赛,KCC2026M1W1D4,"[{'battle_id': '736117264_22_1777120389', 'bat..."
4,2026042601,20260002,"{'team_id': '10903', 'team_name': '桐乡情久', 'tea...","{'team_id': '10028', 'team_name': '长沙TES.A', '...",5,1,2,2026-04-26 12:00:00,2026-04-26 14:28:56,北京,,0,dbtts,单败淘汰赛,KCC2026M1W2D1,"[{'battle_id': '736117264_26_1777176389', 'bat..."

In [35]:
schedule_df.tail()

,match_id,league_id,camp1,camp2,bo,win_camp,status,start_time,end_time,match_address,match_desc,match_stage_seq,match_stage_name,match_stage_desc,cc_match_id,match_battle_video_list
33,2026051401,20260002,"{'team_id': '10000', 'team_name': '待定', 'team_...","{'team_id': '10000', 'team_name': '待定', 'team_...",7,0,0,2026-05-14 19:00:00,,北京,,0,sbtts,双败淘汰赛,KCC2026M3W7D1,[]
34,2026051501,20260002,"{'team_id': '10000', 'team_name': '待定', 'team_...","{'team_id': '10000', 'team_name': '待定', 'team_...",7,0,0,2026-05-15 19:00:00,,北京,,0,sbtts,双败淘汰赛,KCC2026M3W8D1,[]
35,2026051601,20260002,"{'team_id': '10000', 'team_name': '待定', 'team_...","{'team_id': '10000', 'team_name': '待定', 'team_...",7,0,0,2026-05-16 19:00:00,,北京,,0,sbtts,双败淘汰赛,KCC2026M3W9D1,[]
36,2026051701,20260002,"{'team_id': '10000', 'team_name': '待定', 'team_...","{'team_id': '10000', 'team_name': '待定', 'team_...",7,0,0,2026-05-17 19:00:00,,北京,,0,sbtts,双败淘汰赛,KCC2026M3W10D1,[]
37,2026052301,20260002,"{'team_id': '10000', 'team_name': '待定', 'team_...","{'team_id': '10000', 'team_name': '待定', 'team_...",7,0,0,2026-05-23 16:00:00,,上海,,0,js,决赛,KCC2026M4W1D1,[]

In [36]:
# TODO 2.3：保存赛程总表
# 路径：../data/processed/schedule.csv
# 编码：utf-8-sig （Excel 打开不乱码）
# index=False
# 思考：为什么把它放 processed/ 而不是 raw/？
# 提示：raw 是「接口原样」，processed 是「我整理过的结构化表」

schedule_root = Path("../data/processed").resolve()

path = f"{schedule_root}/schedule.csv"

schedule_df.to_csv(path, index=False,encoding='utf-8-sig')

💡 **观察**：

- 一共拉到多少条 battle_id？多少场 match？
- 时间跨度是从什么时候到什么时候？
- `match_id` 和 `battle_id` 的关系是什么？（一对多？数量比？）
- 有没有「未来场次」（还没打的）？模型只能用「已打完」的，需要过滤吗？

---
## 步骤 3 · 批量爬全部比赛

### 思路

拿到所有 battle_id 后，就是个简单的循环。但**不能简单的 `for + fetch_battle`**——要做几件事保命：

| 设计点 | 怎么做 | 为什么 |
|--------|--------|--------|
| 进度可见 | `tqdm` 包一层 | 几百条要跑半小时，没进度条会以为卡住 |
| 单条失败不影响整体 | `try/except` 包 fetch_battle 调用 | 一条失败就 raise = 前面跑过的白跑 |
| 失败要记录 | 用 list 收集 failed_ids | 跑完知道哪些要补爬 |
| 结果分类统计 | 成功 / 业务失败 / 技术失败 | 区别对待 |

### 反爬 vs 进度的取舍

`fetch_battle` 已经内置了 1-2 秒延时。100 场比赛 × 1.5 秒 ≈ 150 秒 ≈ 2.5 分钟。

第二次跑全部命中缓存，秒级完成。所以**第一次慢点没事**——之后修代码、调试都很快。

In [37]:
# TODO 3.1：批量爬
# 框架：
#   battle_ids = schedule_df['battle_id'].unique().tolist()
#   success, failed = [], []
#   for bid in tqdm(battle_ids):
#       try:
#           data = fetch_battle(bid)
#           if data is not None:
#               success.append(bid)
#           else:
#               failed.append((bid, 'fetch returned None'))
#       except Exception as e:
#           failed.append((bid, str(e)))

In [38]:
def fetch_match(match_id) :
	match_url = f"https://prod.comp.smoba.qq.com/leaguesite/match/battles/open?match_id={match_id}"
	battle_list = []
	response = requests.get(url=match_url, headers=HEADERS, timeout=20)
	data_match = response.json()
	for i in range(len(data_match['results'])):
		battle_list.append(data_match['results'][i]['battle_id'])
	return battle_list

In [39]:
schedule_df["match_id"].unique()

<StringArray>
['2026042501', '2026042502', '2026042503', '2026042504', '2026042601',
 '2026042602', '2026042603', '2026042604', '2026042701', '2026042702',
 '2026042703', '2026042704', '2026042801', '2026042802', '2026042803',
 '2026042804', '2026043001', '2026043002', '2026050101', '2026050102',
 '2026050201', '2026050202', '2026050301', '2026050302', '2026050801',
 '2026050802', '2026050901', '2026050902', '2026051001', '2026051002',
 '2026051101', '2026051201', '2026051301', '2026051401', '2026051501',
 '2026051601', '2026051701', '2026052301']
Length: 38, dtype: str

In [40]:
success = []
failed = []
battle_list = []

completed = schedule_df[schedule_df["status"] == 2]#已经完赛的
match_ids = completed["match_id"].unique().tolist()

In [42]:
for match_id in match_ids:
	battle_list.append(fetch_match(match_id))

In [43]:
battle_list

[['736117264_10_1777089898',
  '736117264_11_1777091838',
  '736117264_12_1777093747',
  '736117264_13_1777095778'],
 ['736117264_14_1777099889',
  '736117264_15_1777101864',
  '736117264_16_1777103765',
  '736117264_17_1777105595'],
 ['736117264_18_1777113272',
  '736117264_19_1777114949',
  '736117264_21_1777117059'],
 ['736117264_22_1777120389',
  '736117264_23_1777122032',
  '736117264_24_1777123595'],
 ['736117264_26_1777176389',
  '736117264_27_1777178528',
  '736117264_28_1777180478',
  '736117264_29_1777182144',
  '736117264_30_1777183470'],
 ['736117264_31_1777187214',
  '736117264_32_1777188987',
  '736117264_33_1777190822',
  '736117264_34_1777192390',
  '736117264_35_1777194471'],
 ['736117264_36_1777201256',
  '736117264_37_1777203203',
  '736117264_38_1777205445',
  '736117264_39_1777207738',
  '736117264_40_1777209524'],
 ['736117264_41_1777214738',
  '736117264_42_1777216972',
  '736117264_43_1777218912',
  '736117264_44_1777220644',
  '736117264_45_1777222317'],
 ['736117264_48_1777262688',
  '736117264_49_1777264603',
  '736117264_50_1777266554'],
 ['736117264_10_1777089898',
  '736117264_11_1777091838',
  '736117264_12_1777093747',
  '736117264_13_1777095778'],
 ['736117264_14_1777099889',
  '736117264_15_1777101864',
  '736117264_16_1777103765',
  '736117264_17_1777105595'],
 ['736117264_18_1777113272',
  '736117264_19_1777114949',
  '736117264_21_1777117059'],
 ['736117264_22_1777120389',
  '736117264_23_1777122032',
  '736117264_24_1777123595'],
 ['736117264_26_1777176389',
  '736117264_27_1777178528',
  '736117264_28_1777180478',
  '736117264_29_1777182144',
  '736117264_30_1777183470'],
 ['736117264_31_1777187214',
  '736117264_32_1777188987',
  '736117264_33_1777190822',
  '736117264_34_1777192390',
  '736117264_35_1777194471'],
 ['736117264_36_1777201256',
  '736117264_37_1777203203',
  '736117264_38_1777205445',
  '736117264_39_1777207738',
  '736117264_40_1777209524'],
 ['736117264_41_1777214738',
  '736117264_42_1777216972',
  '736117264_43_1777218912',
  '736117264_44_1777220644',
  '736117264_45_1777222317'],
 ['736117264_48_1777262688',
  '736117264_49_1777264603',
  '736117264_50_1777266554'],
 ['736117264_51_1777270365',
  '736117264_52_1777272165',
  '736117264_53_1777274294',
  '736117264_54_1777277113'],
 ['736117264_55_1777286089',
  '736117264_56_1777287965',
  '736117264_57_1777289572'],
 ['736117264_58_1777293318',
  '736117264_59_1777295254',
  '736117264_60_1777297594'],
 ['736117264_63_1777349064',
  '736117264_66_1777350888',
  '736117264_68_1777352600'],
 ['736117264_70_1777356381',
  '736117264_71_1777358356',
  '736117264_72_1777360256',
  '736117264_73_1777362134',
  '736117264_74_1777363795'],
 ['736117264_75_1777372423',
  '736117264_76_1777374411',
  '736117264_77_1777376224'],
 ['736117264_78_1777379827',
  '736117264_79_1777381653',
  '736117264_80_1777383359',
  '736117264_81_1777385644'],
 ['736117264_86_1777529109',
  '736117264_87_1777531156',
  '736117264_88_1777533000',
  '736117264_89_1777535191',
  '736117264_90_1777536520',
  '736117264_91_1777538507'],
 ['736117264_92_1777547035',
  '736117264_93_1777548955',
  '736117264_94_1777550959',
  '736117264_95_1777552920'],
 ['736117264_99_1777615744',
  '736117264_100_1777617541',
  '736117264_101_1777619308',
  '736117264_102_1777620855',
  '736117264_103_1777622435'],
 ['736117264_104_1777633456',
  '736117264_105_1777635266',
  '736117264_106_1777636904',
  '736117264_107_1777638830',
  '736117264_108_1777641190',
  '736117264_109_1777643014',
  '736117264_110_1777645536'],
 ['736117264_113_1777701775',
  '736117264_114_1777703917',
  '736117264_115_1777705840',
  '736117264_116_1777707756',
  '736117264_117_1777709820',
  '736117264_118_1777711794'],
 ['736117264_119_1777719791',
  '736117264_120_1777721607',
  '736117264_121_1777723302',
  '736117264_122_1777725014',
  '736117264_123_1777726669',
  '736117264_124_1777728759'],
 ['736117264_127_1777788358',
  '736117264_128_1777790473',
  '736117264_129_1777792482',
  '736117264_130_1777794428'],
 ['736117264_131_1777806229',
  '736117264_132_1777808351',
  '736117264_133_1777809862',
  '736117264_134_1777811704',
  '736117264_138_1777813272',
  '736117264_140_1777815010'],
 ['736117264_14_1778220316',
  '736117264_15_1778222070',
  '736117264_16_1778224044',
  '736117264_17_1778225827',
  '736117264_18_1778227410'],
 ['736117264_19_1778238263',
  '736117264_20_1778240239',
  '736117264_21_1778242079',
  '736117264_22_1778243842',
  '736117264_23_1778245253',
  '736117264_24_1778247191',
  '736117264_25_1778248850'],
 ['736117264_30_1778306792',
  '736117264_31_1778308620',
  '736117264_32_1778310429',
  '736117264_33_1778312261'],
 ['736117264_34_1778324655',
  '736117264_35_1778326511',
  '736117264_36_1778328510',
  '736117264_37_1778330358',
  '736117264_38_1778331975']]

In [44]:
for list_id in battle_list:
	for battle_id in tqdm(list_id):

		try:
			data = fetch_battle(battle_id)
			if data is None:
				if battle_id not in failed:
					failed.append((battle_id, 'fetch returned None'))
			else:
				if battle_id not in success:
					success.append(battle_id)
		except Exception as e:
			if battle_id not in failed:
				failed.set((battle_id, str(e)))

  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_10_1777089898]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_11_1777091838]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_12_1777093747]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_13_1777095778]

100%|██████████| 4/4 [00:00<00:00, 417.95it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_14_1777099889]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_15_1777101864]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_16_1777103765]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_17_1777105595]

100%|██████████| 4/4 [00:00<00:00, 388.77it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_18_1777113272]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_19_1777114949]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_21_1777117059]

100%|██████████| 3/3 [00:00<00:00, 369.34it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_22_1777120389]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_23_1777122032]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_24_1777123595]

100%|██████████| 3/3 [00:00<00:00, 478.98it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_26_1777176389]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_27_1777178528]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_28_1777180478]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_29_1777182144]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_30_1777183470]

100%|██████████| 5/5 [00:00<00:00, 433.35it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_31_1777187214]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_32_1777188987]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_33_1777190822]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_34_1777192390]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_35_1777194471]

100%|██████████| 5/5 [00:00<00:00, 418.24it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_36_1777201256]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_37_1777203203]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_38_1777205445]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_39_1777207738]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_40_1777209524]

100%|██████████| 5/5 [00:00<00:00, 419.98it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_41_1777214738]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_42_1777216972]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_43_1777218912]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_44_1777220644]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_45_1777222317]

100%|██████████| 5/5 [00:00<00:00, 390.18it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_48_1777262688]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_49_1777264603]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_50_1777266554]

100%|██████████| 3/3 [00:00<00:00, 498.39it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_10_1777089898]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_11_1777091838]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_12_1777093747]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_13_1777095778]

100%|██████████| 4/4 [00:00<00:00, 563.47it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_14_1777099889]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_15_1777101864]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_16_1777103765]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_17_1777105595]

100%|██████████| 4/4 [00:00<00:00, 627.07it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_18_1777113272]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_19_1777114949]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_21_1777117059]

100%|██████████| 3/3 [00:00<00:00, 657.90it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_22_1777120389]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_23_1777122032]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_24_1777123595]

100%|██████████| 3/3 [00:00<00:00, 530.70it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_26_1777176389]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_27_1777178528]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_28_1777180478]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_29_1777182144]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_30_1777183470]

100%|██████████| 5/5 [00:00<00:00, 532.69it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_31_1777187214]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_32_1777188987]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_33_1777190822]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_34_1777192390]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_35_1777194471]

100%|██████████| 5/5 [00:00<00:00, 586.70it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_36_1777201256]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_37_1777203203]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_38_1777205445]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_39_1777207738]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_40_1777209524]

100%|██████████| 5/5 [00:00<00:00, 612.33it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_41_1777214738]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_42_1777216972]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_43_1777218912]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_44_1777220644]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_45_1777222317]

100%|██████████| 5/5 [00:00<00:00, 630.91it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_48_1777262688]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_49_1777264603]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_50_1777266554]

100%|██████████| 3/3 [00:00<00:00, 534.24it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_51_1777270365]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_52_1777272165]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_53_1777274294]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_54_1777277113]

100%|██████████| 4/4 [00:00<00:00, 408.13it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_55_1777286089]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_56_1777287965]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_57_1777289572]

100%|██████████| 3/3 [00:00<00:00, 407.49it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_58_1777293318]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_59_1777295254]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_60_1777297594]

100%|██████████| 3/3 [00:00<00:00, 340.66it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_63_1777349064]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_66_1777350888]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_68_1777352600]

100%|██████████| 3/3 [00:00<00:00, 487.60it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_70_1777356381]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_71_1777358356]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_72_1777360256]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_73_1777362134]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_74_1777363795]

100%|██████████| 5/5 [00:00<00:00, 395.57it/s]
  0%|          | 0/3 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_75_1777372423]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_76_1777374411]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_77_1777376224]

100%|██████████| 3/3 [00:00<00:00, 490.31it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_78_1777379827]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_79_1777381653]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_80_1777383359]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_81_1777385644]

100%|██████████| 4/4 [00:00<00:00, 433.58it/s]
  0%|          | 0/6 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_86_1777529109]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_87_1777531156]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_88_1777533000]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_89_1777535191]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_90_1777536520]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_91_1777538507]

100%|██████████| 6/6 [00:00<00:00, 399.05it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_92_1777547035]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_93_1777548955]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_94_1777550959]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_95_1777552920]

100%|██████████| 4/4 [00:00<00:00, 384.77it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_99_1777615744]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_100_1777617541]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_101_1777619308]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_102_1777620855]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_103_1777622435]

100%|██████████| 5/5 [00:00<00:00, 411.46it/s]
  0%|          | 0/7 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_104_1777633456]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_105_1777635266]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_106_1777636904]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_107_1777638830]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_108_1777641190]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_109_1777643014]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_110_1777645536]

100%|██████████| 7/7 [00:00<00:00, 513.78it/s]
  0%|          | 0/6 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_113_1777701775]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_114_1777703917]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_115_1777705840]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_116_1777707756]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_117_1777709820]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_118_1777711794]

100%|██████████| 6/6 [00:00<00:00, 426.07it/s]
  0%|          | 0/6 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_119_1777719791]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_120_1777721607]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_121_1777723302]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_122_1777725014]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_123_1777726669]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_124_1777728759]

100%|██████████| 6/6 [00:00<00:00, 385.44it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_127_1777788358]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_128_1777790473]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_129_1777792482]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_130_1777794428]

100%|██████████| 4/4 [00:00<00:00, 467.19it/s]
  0%|          | 0/6 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_131_1777806229]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_132_1777808351]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_133_1777809862]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_134_1777811704]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_138_1777813272]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_140_1777815010]

100%|██████████| 6/6 [00:00<00:00, 429.89it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_14_1778220316]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_15_1778222070]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_16_1778224044]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_17_1778225827]
2026-05-09 23:29:29 | src.crawler.api_client | INFO | [命中缓存，736117264_18_1778227410]

100%|██████████| 5/5 [00:00<00:00, 413.98it/s]
  0%|          | 0/7 [00:00<?, ?it/s]

2026-05-09 23:29:33 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:29:34 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_19_1778238263.json

 14%|█▍        | 1/7 [00:05<00:30,  5.13s/it]

2026-05-09 23:29:37 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:29:39 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_20_1778240239.json

 29%|██▊       | 2/7 [00:09<00:24,  4.89s/it]

2026-05-09 23:29:42 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:29:43 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_21_1778242079.json

 43%|████▎     | 3/7 [00:14<00:18,  4.62s/it]

2026-05-09 23:29:52 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:29:53 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_22_1778243842.json

 57%|█████▋    | 4/7 [00:23<00:20,  6.68s/it]

2026-05-09 23:29:56 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:29:58 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_23_1778245253.json

 71%|███████▏  | 5/7 [00:29<00:12,  6.11s/it]

2026-05-09 23:30:01 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:02 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_24_1778247191.json

 86%|████████▌ | 6/7 [00:32<00:05,  5.31s/it]

2026-05-09 23:30:04 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:05 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_25_1778248850.json

100%|██████████| 7/7 [00:35<00:00,  5.13s/it]
  0%|          | 0/4 [00:00<?, ?it/s]

2026-05-09 23:30:07 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:09 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_30_1778306792.json

 25%|██▌       | 1/4 [00:03<00:10,  3.54s/it]

2026-05-09 23:30:11 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:12 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_31_1778308620.json

 50%|█████     | 2/4 [00:07<00:07,  3.50s/it]

2026-05-09 23:30:18 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:19 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_32_1778310429.json

 75%|███████▌  | 3/4 [00:14<00:05,  5.26s/it]

2026-05-09 23:30:25 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:27 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_33_1778312261.json

100%|██████████| 4/4 [00:21<00:00,  5.41s/it]
  0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 23:30:30 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:32 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_34_1778324655.json

 20%|██        | 1/5 [00:05<00:21,  5.39s/it]

2026-05-09 23:30:40 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:41 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_35_1778326511.json

 40%|████      | 2/5 [00:14<00:22,  7.55s/it]

2026-05-09 23:30:45 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:47 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_36_1778328510.json

 60%|██████    | 3/5 [00:20<00:13,  6.74s/it]

2026-05-09 23:30:50 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:51 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_37_1778330358.json

 80%|████████  | 4/5 [00:24<00:05,  5.59s/it]

2026-05-09 23:30:53 | src.crawler.api_client | INFO | 已查询到数据，正在写入数据
2026-05-09 23:30:55 | src.crawler.api_client | INFO | 数据保存成功，路径：D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\raw\736117264_38_1778331975.json

100%|██████████| 5/5 [00:27<00:00,  5.57s/it]

append会出现重复值

In [45]:
# TODO 3.2：跑完后统计 + 保存失败列表
# 1. 成功率：len(success) / 总数
# 2. 文件数核对：len(list(Path('../data/raw').glob('*.json'))) 应该 ≈ len(success)
# 3. 失败列表存成 CSV：../output/failed_ids.csv（方便日后补爬）
success

['736117264_10_1777089898',
 '736117264_11_1777091838',
 '736117264_12_1777093747',
 '736117264_13_1777095778',
 '736117264_14_1777099889',
 '736117264_15_1777101864',
 '736117264_16_1777103765',
 '736117264_17_1777105595',
 '736117264_18_1777113272',
 '736117264_19_1777114949',
 '736117264_21_1777117059',
 '736117264_22_1777120389',
 '736117264_23_1777122032',
 '736117264_24_1777123595',
 '736117264_26_1777176389',
 '736117264_27_1777178528',
 '736117264_28_1777180478',
 '736117264_29_1777182144',
 '736117264_30_1777183470',
 '736117264_31_1777187214',
 '736117264_32_1777188987',
 '736117264_33_1777190822',
 '736117264_34_1777192390',
 '736117264_35_1777194471',
 '736117264_36_1777201256',
 '736117264_37_1777203203',
 '736117264_38_1777205445',
 '736117264_39_1777207738',
 '736117264_40_1777209524',
 '736117264_41_1777214738',
 '736117264_42_1777216972',
 '736117264_43_1777218912',
 '736117264_44_1777220644',
 '736117264_45_1777222317',
 '736117264_48_1777262688',
 '736117264_49_1777264603',
 '736117264_50_1777266554',
 '736117264_51_1777270365',
 '736117264_52_1777272165',
 '736117264_53_1777274294',
 '736117264_54_1777277113',
 '736117264_55_1777286089',
 '736117264_56_1777287965',
 '736117264_57_1777289572',
 '736117264_58_1777293318',
 '736117264_59_1777295254',
 '736117264_60_1777297594',
 '736117264_63_1777349064',
 '736117264_66_1777350888',
 '736117264_68_1777352600',
 '736117264_70_1777356381',
 '736117264_71_1777358356',
 '736117264_72_1777360256',
 '736117264_73_1777362134',
 '736117264_74_1777363795',
 '736117264_75_1777372423',
 '736117264_76_1777374411',
 '736117264_77_1777376224',
 '736117264_78_1777379827',
 '736117264_79_1777381653',
 '736117264_80_1777383359',
 '736117264_81_1777385644',
 '736117264_86_1777529109',
 '736117264_87_1777531156',
 '736117264_88_1777533000',
 '736117264_89_1777535191',
 '736117264_90_1777536520',
 '736117264_91_1777538507',
 '736117264_92_1777547035',
 '736117264_93_1777548955',
 '736117264_94_1777550959',
 '736117264_95_1777552920',
 '736117264_99_1777615744',
 '736117264_100_1777617541',
 '736117264_101_1777619308',
 '736117264_102_1777620855',
 '736117264_103_1777622435',
 '736117264_104_1777633456',
 '736117264_105_1777635266',
 '736117264_106_1777636904',
 '736117264_107_1777638830',
 '736117264_108_1777641190',
 '736117264_109_1777643014',
 '736117264_110_1777645536',
 '736117264_113_1777701775',
 '736117264_114_1777703917',
 '736117264_115_1777705840',
 '736117264_116_1777707756',
 '736117264_117_1777709820',
 '736117264_118_1777711794',
 '736117264_119_1777719791',
 '736117264_120_1777721607',
 '736117264_121_1777723302',
 '736117264_122_1777725014',
 '736117264_123_1777726669',
 '736117264_124_1777728759',
 '736117264_127_1777788358',
 '736117264_128_1777790473',
 '736117264_129_1777792482',
 '736117264_130_1777794428',
 '736117264_131_1777806229',
 '736117264_132_1777808351',
 '736117264_133_1777809862',
 '736117264_134_1777811704',
 '736117264_138_1777813272',
 '736117264_140_1777815010',
 '736117264_14_1778220316',
 '736117264_15_1778222070',
 '736117264_16_1778224044',
 '736117264_17_1778225827',
 '736117264_18_1778227410',
 '736117264_19_1778238263',
 '736117264_20_1778240239',
 '736117264_21_1778242079',
 '736117264_22_1778243842',
 '736117264_23_1778245253',
 '736117264_24_1778247191',
 '736117264_25_1778248850',
 '736117264_30_1778306792',
 '736117264_31_1778308620',
 '736117264_32_1778310429',
 '736117264_33_1778312261',
 '736117264_34_1778324655',
 '736117264_35_1778326511',
 '736117264_36_1778328510',
 '736117264_37_1778330358',
 '736117264_38_1778331975']

In [46]:
failed

[]

In [47]:
battle_id_list = []
for list_id in battle_list:
	for battle_id in list_id:
		battle_id_list.append(battle_id)

In [48]:
battle_id_list

['736117264_10_1777089898',
 '736117264_11_1777091838',
 '736117264_12_1777093747',
 '736117264_13_1777095778',
 '736117264_14_1777099889',
 '736117264_15_1777101864',
 '736117264_16_1777103765',
 '736117264_17_1777105595',
 '736117264_18_1777113272',
 '736117264_19_1777114949',
 '736117264_21_1777117059',
 '736117264_22_1777120389',
 '736117264_23_1777122032',
 '736117264_24_1777123595',
 '736117264_26_1777176389',
 '736117264_27_1777178528',
 '736117264_28_1777180478',
 '736117264_29_1777182144',
 '736117264_30_1777183470',
 '736117264_31_1777187214',
 '736117264_32_1777188987',
 '736117264_33_1777190822',
 '736117264_34_1777192390',
 '736117264_35_1777194471',
 '736117264_36_1777201256',
 '736117264_37_1777203203',
 '736117264_38_1777205445',
 '736117264_39_1777207738',
 '736117264_40_1777209524',
 '736117264_41_1777214738',
 '736117264_42_1777216972',
 '736117264_43_1777218912',
 '736117264_44_1777220644',
 '736117264_45_1777222317',
 '736117264_48_1777262688',
 '736117264_49_1777264603',
 '736117264_50_1777266554',
 '736117264_10_1777089898',
 '736117264_11_1777091838',
 '736117264_12_1777093747',
 '736117264_13_1777095778',
 '736117264_14_1777099889',
 '736117264_15_1777101864',
 '736117264_16_1777103765',
 '736117264_17_1777105595',
 '736117264_18_1777113272',
 '736117264_19_1777114949',
 '736117264_21_1777117059',
 '736117264_22_1777120389',
 '736117264_23_1777122032',
 '736117264_24_1777123595',
 '736117264_26_1777176389',
 '736117264_27_1777178528',
 '736117264_28_1777180478',
 '736117264_29_1777182144',
 '736117264_30_1777183470',
 '736117264_31_1777187214',
 '736117264_32_1777188987',
 '736117264_33_1777190822',
 '736117264_34_1777192390',
 '736117264_35_1777194471',
 '736117264_36_1777201256',
 '736117264_37_1777203203',
 '736117264_38_1777205445',
 '736117264_39_1777207738',
 '736117264_40_1777209524',
 '736117264_41_1777214738',
 '736117264_42_1777216972',
 '736117264_43_1777218912',
 '736117264_44_1777220644',
 '736117264_45_1777222317',
 '736117264_48_1777262688',
 '736117264_49_1777264603',
 '736117264_50_1777266554',
 '736117264_51_1777270365',
 '736117264_52_1777272165',
 '736117264_53_1777274294',
 '736117264_54_1777277113',
 '736117264_55_1777286089',
 '736117264_56_1777287965',
 '736117264_57_1777289572',
 '736117264_58_1777293318',
 '736117264_59_1777295254',
 '736117264_60_1777297594',
 '736117264_63_1777349064',
 '736117264_66_1777350888',
 '736117264_68_1777352600',
 '736117264_70_1777356381',
 '736117264_71_1777358356',
 '736117264_72_1777360256',
 '736117264_73_1777362134',
 '736117264_74_1777363795',
 '736117264_75_1777372423',
 '736117264_76_1777374411',
 '736117264_77_1777376224',
 '736117264_78_1777379827',
 '736117264_79_1777381653',
 '736117264_80_1777383359',
 '736117264_81_1777385644',
 '736117264_86_1777529109',
 '736117264_87_1777531156',
 '736117264_88_1777533000',
 '736117264_89_1777535191',
 '736117264_90_1777536520',
 '736117264_91_1777538507',
 '736117264_92_1777547035',
 '736117264_93_1777548955',
 '736117264_94_1777550959',
 '736117264_95_1777552920',
 '736117264_99_1777615744',
 '736117264_100_1777617541',
 '736117264_101_1777619308',
 '736117264_102_1777620855',
 '736117264_103_1777622435',
 '736117264_104_1777633456',
 '736117264_105_1777635266',
 '736117264_106_1777636904',
 '736117264_107_1777638830',
 '736117264_108_1777641190',
 '736117264_109_1777643014',
 '736117264_110_1777645536',
 '736117264_113_1777701775',
 '736117264_114_1777703917',
 '736117264_115_1777705840',
 '736117264_116_1777707756',
 '736117264_117_1777709820',
 '736117264_118_1777711794',
 '736117264_119_1777719791',
 '736117264_120_1777721607',
 '736117264_121_1777723302',
 '736117264_122_1777725014',
 '736117264_123_1777726669',
 '736117264_124_1777728759',
 '736117264_127_1777788358',
 '736117264_128_1777790473',
 '736117264_129_1777792482',
 '736117264_130_1777794428',
 '736117264_131_1777806229',
 '736117264_132_1777808351',
 '736117264_133_1777809862',
 '736117264_134_1777811704',
 '736117264_138_1777813272',
 '736117264_140_1777815010',
 '736117264_14_1778220316',
 '736117264_15_1778222070',
 '736117264_16_1778224044',
 '736117264_17_1778225827',
 '736117264_18_1778227410',
 '736117264_19_1778238263',
 '736117264_20_1778240239',
 '736117264_21_1778242079',
 '736117264_22_1778243842',
 '736117264_23_1778245253',
 '736117264_24_1778247191',
 '736117264_25_1778248850',
 '736117264_30_1778306792',
 '736117264_31_1778308620',
 '736117264_32_1778310429',
 '736117264_33_1778312261',
 '736117264_34_1778324655',
 '736117264_35_1778326511',
 '736117264_36_1778328510',
 '736117264_37_1778330358',
 '736117264_38_1778331975']

In [49]:
len(success)/len(battle_id_list)

0.774390243902439

In [50]:
len(list(Path("../data/raw").glob("*.json")))

127

In [51]:
pd.DataFrame(failed).to_csv("../output/failed.csv")

💡 **观察**：

- 成功率多少？低于 95% 就要看失败原因 100%
- 失败的 battle_id 集中在某些场次吗？还是随机分布？没有
- 大部分失败的原因是什么？（业务错误 vs 技术错误的比例）无
- 第一次跑总耗时多少？（用来评估爬虫的可扩展性）

---
## 步骤 4 · 沉淀到 src 模块

### 任务

把 `fetch_schedule()` 函数迁移到 `src/crawler/schedule_crawler.py`。

迁移规范（同 notebook 01 步骤 7）：
1. docstring 写清楚参数、返回值
2. 类型注解 `def fetch_schedule(league_id: int) -> list[dict]:`
3. 用 `from src.utils.logger import get_logger` 拿 logger
4. URL 和 Headers 抽到 `src/config.py`（如果赛程接口的 Headers 跟单场不一样，单独加常量）

迁移完在下面验证：

In [52]:
# TODO 4.1：从 src 导入 fetch_schedule 验证
# from src.crawler.schedule_crawler import fetch_schedule
# rows = fetch_schedule(20260002)
# print(len(rows), rows[0])

from src.crawler.schedule_crawler import fetch_schedule

rows =fetch_schedule(20260002)
print(len(rows),rows.iloc[0])

2026-05-09 23:31:05 | src.crawler.schedule_crawler | INFO | 拉取赛程成功：38 场 match
2026-05-09 23:31:05 | src.crawler.schedule_crawler | INFO | 赛程已保存至 D:\AI数据分析\项目作品集\02-KPL实时胜率预测系统\data\processed\schedule.csv
38 match_id                                                          2026042501
league_id                                                           20260002
camp1                      {'team_id': '10005', 'team_name': 'KSG', 'team...
camp2                      {'team_id': '10017', 'team_name': '广州TTG', 'te...
bo                                                                         5
win_camp                                                                   2
status                                                                     2
start_time                                               2026-04-25 12:00:00
end_time                                                 2026-04-25 14:12:39
match_address                                                             北京
match_desc
match_stage_seq                                                            0
match_stage_name                                                       dbtts
match_stage_desc                                                       单败淘汰赛
cc_match_id                                                    KCC2026M1W1D1
match_battle_video_list    [{'battle_id': '736117264_10_1777089898', 'bat...
Name: 0, dtype: object

---
## ✅ 完成自检

- [ ] `fetch_schedule()` 能拉到完整赛程
- [ ] `data/processed/schedule.csv` 已生成，可以用 Excel 打开看
- [ ] 批量爬完成，成功率 ≥ 95%
- [ ] 失败的 battle_id 写到了 `output/failed_ids.csv`
- [ ] `data/raw/` 下囤了几十个原始 JSON
- [ ] `src/crawler/schedule_crawler.py` 迁移完成

## 🎯 完成后跟我汇报

```
1. 我做了什么：______
2. 我的思考：______
   - 这个赛事一共多少场？
   - 失败的占比 / 失败的原因
3. 我想确认：______
```